name: "Smoke test"
inputs:
  resource:
    description: "Resource to test"
    required: true
  type:
    description: "Resource type"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v4

    - name: Build resource
      id: build_resource
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.resource }} ${{ inputs.type }}

    - name: Test resource
      id: test_resource
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.resource }} ${{ inputs.type }}
