name: Publish prebuild image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: image/joomla
          imageName: ${{ env.REGISTRY }}/${{ github.repository}}
          cacheFrom: ${{ env.REGISTRY }}/${{ github.repository}}
          push: always
