name: "CI - Test Image"
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            joomla: ./**/images/joomla/**

  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        images: ${{ fromJSON(needs.detect-changes.outputs.images) }}
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test for '${{ matrix.images }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.images }}"
          type: "images"
